"""init

Revision ID: 051da6194764
Revises: 
Create Date: 2025-05-12 17:05:06.712028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051da6194764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('long_url', sa.String(length=2048), nullable=False),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('url_id'),
    sa.UniqueConstraint('short_url')
    )
    op.create_index(op.f('ix_urls_url_id'), 'urls', ['url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_url_id'), table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
